import Footer from "./components/Shared/Footer";
import Nav from "./components/Shared/Nav";
import TopHeader from "./components/Shared/components/TopHeader";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopHeader />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
